### PR TITLE
Fixes: #54 add enhanced_readme

### LINKED ISSUE #54: Update Readme
What's missing in this repository!!

A README file is essential in any given repository because it serves as the primary source of information about the project. It provides an overview of the project's purpose, how to install and use it, and any necessary prerequisites. Additionally, the README often includes guidelines for contributing, links to documentation, and contact information for the maintainers. This file ensures that both new and returning users can easily understand the project's scope, setup, and usage, thereby enhancing the project's accessibility and fostering collaboration. By consolidating all critical information in one place, a README file significantly improves the user experience and facilitates effective project management.

Kindly assign this issue to me under GSSoC'24

### PR DESCRIPTION
**Pull request by aasthakourav20**
Fixes: #54 

Added quick features of the project ,  which will create convenience to the users/Contributors . Added imp contributing guidelines.

- Documentation update

### CODE REVIEW

**Comment by aasthakourav20** [comment]
Hey @TusharAMD , changes are done !! please review it.

**Comment by TusharAMD** [comment]
https://github.com/TusharAMD/SuperSpeechSaga/blob/master/CONTRIBUTION.md
This the contribution guideline, but in readme you have written yet to update. can you please change it?

**Comment by aasthakourav20** [comment]
> https://github.com/TusharAMD/SuperSpeechSaga/blob/master/CONTRIBUTION.md This the contribution guideline, but in readme you have written yet to update. can you please change it?

Hey , required changes done

**Comment by aasthakourav20** [comment]
Hey @TusharAMD as my PR is merged kindly assign this issue to me under GSSoC and add labels like level1 , level2 , level3.
As adding labels is important to get points.

**Pull request merged**
