### PR TITLE
Chapter 1 story added

### PR DESCRIPTION
**Pull request by poojaharihar03**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
solved Pr #55
## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [x] Other (specify): Story 

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]
basic storyline is ready characters are created and scenarios are built based on user's method of handling the issue some points can be given to users.

### CODE REVIEW

**Comment by poojaharihar03** [comment]
@TusharAMD if any changes let me know.

**Comment by TusharAMD** [comment]
Awesome @poojaharihar03 your PR has been merged 🎉

**Comment by poojaharihar03** [comment]
hi @TusharAMD .
is it possible to close pr?

because this contribution is not shown on the leaderboard.

**Comment by TusharAMD** [comment]
@poojaharihar03 it was closed but levels were not assigned here. Did it now.

**Pull request merged**
